### ISSUE TITLE
Dollar sign

### ISSUE THREAD

**Issue by bugggggggg** [polarwinkel/mdtex2html#1]
Hi, can you show how to show dollar sign at the generated image with `mdtex2html.convert`

**Comment by polarwinkel** [comment]
Hi bugggggggg,
thanks for your feedback, you are right, `$` should be escapable.
I fixed it so that `mdtex2html.convert('\$')` now returns `<p>$</p>`, just like it is done in LaTeX.
I'll still do some testing on existing mdtex-code to be sure there is no unwanted side effect and will commit it as a new release in the next days if all is fine.

**Comment by polarwinkel** [comment]
All test were fine, so just use the latest version (v1.3.0) and add a $-sign in your text with `\$`!

**Comment by bugggggggg** [comment]
thanks for the fix! ^_^
